# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from ast import operator
from re import X
from PyQt5 import QtCore, QtGui, QtWidgets
#============================================operation
operator1=""
operator=""
def btnClick(num):
    global operator,operator1
    if operator1=="":
        operator=operator+str(num)
        ui.lblInput.setText(operator)
    elif operator1!="":
        if num=="/" or num=="*" or num=="-" or num=="+":
            operator=operator1+str(num)
            ui.lblInput.setText(operator)
        else:
            operator1=""
            operator=operator+str(num)
            ui.lblInput.setText(operator)
    else:
        print('error')
def btnClear():
    global operator,operator1
    operator=""
    operator1=""
    ui.lblInput.setText("0")
    
    
def btnEql():
    try:
        global operator,operator1
        sumup=str(eval(operator))
        ui.lblInput.setText(sumup)
        operator1=sumup
        operator=""
    except ZeroDivisionError:
        ui.lblInput.setText("Error")
        operator1=""
        operator=""
    except SyntaxError:
        operator1=operator.replace(operator[len(operator)-1],"")
        ui.lblInput.setText(operator1)
        operator=""
#===========================================================================UI
class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.setEnabled(True)
        Calculator.resize(239, 328)
        Calculator.setMouseTracking(False)
        Calculator.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        #----------------------------------------------7
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setGeometry(QtCore.QRect(20, 110, 50, 50))
        self.btn7.setObjectName("btn7")
        self.btn7.clicked.connect(lambda:btnClick("7"))
        #----------------------------------------------8
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setGeometry(QtCore.QRect(70, 110, 50, 50))
        self.btn8.setObjectName("btn8")
        self.btn8.clicked.connect(lambda:btnClick("8"))
        #----------------------------------------------9
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setGeometry(QtCore.QRect(120, 110, 50, 50))
        self.btn9.setObjectName("btn9")
        self.btn9.clicked.connect(lambda:btnClick("9"))
        #----------------------------------------------4
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setGeometry(QtCore.QRect(20, 160, 50, 50))
        self.btn4.setObjectName("btn4")
        self.btn4.clicked.connect(lambda:btnClick("4"))
        #----------------------------------------------6
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setGeometry(QtCore.QRect(120, 160, 50, 50))
        self.btn6.setObjectName("btn6")
        self.btn6.clicked.connect(lambda:btnClick("6"))
        #----------------------------------------------5
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setGeometry(QtCore.QRect(70, 160, 50, 50))
        self.btn5.setObjectName("btn5")
        self.btn5.clicked.connect(lambda:btnClick("5"))
        #----------------------------------------------3
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setGeometry(QtCore.QRect(120, 210, 50, 50))
        self.btn3.setObjectName("btn3")
        self.btn3.clicked.connect(lambda:btnClick("3"))
        #----------------------------------------------2
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(70, 210, 50, 50))
        self.btn2.setObjectName("btn2")
        self.btn2.clicked.connect(lambda:btnClick("2"))
        #----------------------------------------------/
        self.btnDivision = QtWidgets.QPushButton(self.centralwidget)
        self.btnDivision.setGeometry(QtCore.QRect(120, 260, 50, 50))
        self.btnDivision.setObjectName("btnDivision")
        self.btnDivision.clicked.connect(lambda:btnClick("/"))
        #----------------------------------------------1
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(20, 210, 50, 50))
        self.btn1.setObjectName("btn1")
        self.btn1.clicked.connect(lambda:btnClick("1"))
        #----------------------------------------------.
        self.btnDot = QtWidgets.QPushButton(self.centralwidget)
        self.btnDot.setGeometry(QtCore.QRect(70, 260, 50, 50))
        self.btnDot.setObjectName("btnDot")
        self.btnDot.clicked.connect(lambda:btnClick("."))
        #----------------------------------------------0
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setGeometry(QtCore.QRect(20, 260, 50, 50))
        self.btn0.setObjectName("btn0")
        self.btn0.clicked.connect(lambda:btnClick("0"))
        #----------------------------------------------_
        self.btnMin = QtWidgets.QPushButton(self.centralwidget)
        self.btnMin.setGeometry(QtCore.QRect(170, 110, 50, 50))
        self.btnMin.setObjectName("btnMin")
        self.btnMin.clicked.connect(lambda:btnClick("-"))
        #----------------------------------------------=
        self.btnEql = QtWidgets.QPushButton(self.centralwidget)
        self.btnEql.setGeometry(QtCore.QRect(170, 260, 50, 50))
        self.btnEql.setObjectName("btnEql")
        self.btnEql.clicked.connect(lambda:btnEql())
        #----------------------------------------------+
        self.btnPlus = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlus.setGeometry(QtCore.QRect(170, 160, 50, 50))
        self.btnPlus.setObjectName("btnPlus")
        self.btnPlus.clicked.connect(lambda:btnClick("+"))
        #----------------------------------------------x
        self.btnMulty = QtWidgets.QPushButton(self.centralwidget)
        self.btnMulty.setGeometry(QtCore.QRect(170, 210, 50, 50))
        self.btnMulty.setObjectName("btnMulty")
        self.btnMulty.clicked.connect(lambda:btnClick("*"))
        #----------------------------------------------lbl
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(20, 20, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lblInput.setFont(font)
        self.lblInput.setTabletTracking(False)
        self.lblInput.setAutoFillBackground(True)
        self.lblInput.setTextFormat(QtCore.Qt.AutoText)
        self.lblInput.setScaledContents(False)
        self.lblInput.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblInput.setWordWrap(False)
        self.lblInput.setOpenExternalLinks(False)
        self.lblInput.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.lblInput.setObjectName("lblInput")
        #----------------------------------------------C
        self.btnClear = QtWidgets.QPushButton(self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(20, 80, 50, 31))
        self.btnClear.setObjectName("btnClear")
        self.btnClear.clicked.connect(lambda:btnClear())
        #----------------------------------------------|
        Calculator.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)
        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)
    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.btn7.setText(_translate("Calculator", "7"))
        self.btn8.setText(_translate("Calculator", "8"))
        self.btn9.setText(_translate("Calculator", "9"))
        self.btn4.setText(_translate("Calculator", "4"))
        self.btn6.setText(_translate("Calculator", "6"))
        self.btn5.setText(_translate("Calculator", "5"))
        self.btn3.setText(_translate("Calculator", "3"))
        self.btn2.setText(_translate("Calculator", "2"))
        self.btnDivision.setText(_translate("Calculator", "/"))
        self.btn1.setText(_translate("Calculator", "1"))
        self.btnDot.setText(_translate("Calculator", "."))
        self.btn0.setText(_translate("Calculator", "0"))
        self.btnMin.setText(_translate("Calculator", "-"))
        self.btnEql.setText(_translate("Calculator", "="))
        self.btnPlus.setText(_translate("Calculator", "+"))
        self.btnMulty.setText(_translate("Calculator", "*"))
        self.lblInput.setText(_translate("Calculator", "0"))
        self.btnClear.setText(_translate("Calculator", "c"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
    
#==============================================================End